title: HaTeMiLe
description: Improving accessibility for web pages. 
author: Carlson Santana Cruz
logo: /static/img/avatar.png
github: https://github.com/hatemile
about: Improving accessibility for web pages.

baseurl: ""
url: ""

disqus_enabled: false
disqus_shortname: aboutashu
google_analytics: UA-116147522-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

compress_html:
  clippings: all
  comments: all
